### ISSUE TITLE
Refactor so that eth-json-rpc endpoints use GraphQL to interface with Postgres

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-server#52]
Rather than interfacing directly through a pg connection

**Comment by srwadleigh** [comment]
To add some context from previous discussions, and this is kind of a rough overview from a sysop perspective so there could be per service requirements that weren't taken into account, further refinement etc.

My thinking here is that `arch0-1 vulcanize geth` talks directly to `db0-1 postgresql`, then `db0-1 postgraphile end points` sit in front of each database and become the central place all other database driven services talk to. Likewise `arch0-1 ipld-eth-server` talks directly to vulcanize geth and all other services talk only to the end points that ipld presents.

If ipld-eth-server itself is creating postgraphile endpoints maybe that first graphql layer sitting on the db0-1 becomes redundant but I think this at least begins to paint a picture of centralizing the access paths different services take rather than having everything reaching directly to the database and geth.

**Comment by AFDudley** [comment]
Seems as though this was resolved elsewhere.
